### ISSUE TITLE
SSLHandshakeException

### ISSUE THREAD

**Issue by mangstadt** [mangstadt/OakBot#10]
May 14, 2015 1:46:08 PM oakbot.chat.StackoverflowChat executeWithRetries
INFO: Sleeping for 10000 ms before resending the request...
May 14, 2015 1:47:21 PM oakbot.Main$1 uncaughtException
SEVERE: Uncaught exception thrown.
javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:275)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:254)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:123)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:318)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at oakbot.chat.StackoverflowChat.executeWithRetries(StackoverflowChat.java:287)
	at oakbot.chat.StackoverflowChat.executeWithRetries(StackoverflowChat.java:250)
	at oakbot.chat.StackoverflowChat.executeWithRetriesJson(StackoverflowChat.java:225)
	at oakbot.chat.StackoverflowChat.getMessages(StackoverflowChat.java:131)
	at oakbot.chat.StackoverflowChat.getNewMessages(StackoverflowChat.java:168)
	at oakbot.bot.Bot.connect(Bot.java:84)
	at oakbot.Main.main(Main.java:121)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
	... 23 more

**Comment by mangstadt** [comment]
Fixed
